[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "6crw656Yy1M7AMf9eymEthcPGb7WNHH63a1m8Ben8ynJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/workspace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
